language: go

go:
  - 1.10.x

before_install:
  - go get -t -v ./...
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go test -coverprofile c.out ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
